### ISSUE TITLE
verify-packed-objects panics.

### ISSUE THREAD

**Issue by jbrukh** [jbrukh/ggit#39]
This may be specific to my repo. See if you can reproduce.

406c8f39ff02:ggit brukhman$ ggit verify-packed-objects
Unrecognized pack object type: 0 panic: Could not find object with offset 0. Closest match was 0.

goroutine 1 [running]:
github.com/jbrukh/ggit/api.panicErrf(0x149c68, 0x3b, 0x3066bc38, 0x2)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/parser.go:53 +0x6a
github.com/jbrukh/ggit/api.(_Pack).findObjectByOffset(0x1070d7b0, 0x0, 0x0, 0x1, 0x1, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:584 +0x12a
github.com/jbrukh/ggit/api.(_Pack).parseDeltaEntry(0x1070d7b0, 0x1069d001, 0xa4, 0xa4, 0x106d3300, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:531 +0x18f
github.com/jbrukh/ggit/api.(_Pack).parseEntry(0x1070d7b0, 0x2, 0x106af7e0, 0x5db)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:378 +0xf9
github.com/jbrukh/ggit/api.objectsFromPacks(0x10675340, 0x2, 0x2, 0x10727000, 0x5db, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:190 +0x154
github.com/jbrukh/ggit/api.(_DiskRepository).PackedObjects(0x10661c80, 0x10662330, 0x10661c80)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/disk_repository.go:179 +0x72
github.com/jbrukh/ggit/builtin.(*VerifyPackedObjectsBuiltin).Execute(0x214ce8, 0x10661ca0, 0x10664010)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/builtin/verify_packed_objects.go:35 +0x8a
main.main()
    /Users/brukhman/other/src/github.com/jbrukh/ggit/cmd/ggit/ggit.go:83 +0x4c6

goroutine 2 [syscall]:
created by runtime.main
    /usr/local/go/src/pkg/runtime/proc.c:221

goroutine 3 [finalizer wait]:
created by runtime.gc
    /usr/local/go/src/pkg/runtime/mgc0.c:882

**Comment by MikeBosw** [comment]
No, this was not specific to your repo. This was me learning something new about Go closures.

**Comment by jbrukh** [comment]
Awesome.

On Oct 31, 2012, at 10:53 PM, MikeBosw notifications@github.com wrote:

No, this was not specific to your repo. This was me learning something new
about Go closures.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jbrukh/ggit/issues/39#issuecomment-9969493.

**Comment by jbrukh** [comment]
What did we learn about Go closures? :)
