### ISSUE TITLE
ggcompare fails on libgit2 git repo with incorrect date.

### ISSUE THREAD

**Issue by jbrukh** [jbrukh/ggit#40]
found a mismatch in object 725 (23f8588dde934e8f33c263c6d8359b2ae095f863)...
GIT -----------------------
object c5b97d5ae6c19d5c5df71a34c7fbeeda2479ccbc
type commit
tag v0.1.0
tagger Scott Chacon schacon@gmail.com Tue Nov 23 15:53:50 2010 -0800

tagging initial release of libgit2

GGIT -----------------------
object c5b97d5ae6c19d5c5df71a34c7fbeeda2479ccbc
type commit
tag v0.1.0
tagger Scott Chacon schacon@gmail.com Tue Nov 23 18:53:50 2010 -0800

tagging initial release of libgit2

diff -----------------------
object c5b97d5ae6c19d5c5df71a34c7fbeeda2479ccbc
type commit
tag v0.1.0
tagger Scott Chacon schacon@gmail.com Tue Nov 23 1
theirs: 5:53:50 2010 -0800
ours:   8:53:50 2010 -0800

**Comment by MikeBosw** [comment]
Yeah, I saw this too - I'm using git://github.com/twitter/bootstrap.git to
reproduce it.

We should consider switching from cat-file -p to cat-file <type> <oid> for
ggcompare. The former is a "porcelain" command that isn't intended for API
use from what I understand. I've started some work to this end.

**Comment by jbrukh** [comment]
Still, what could explain the 3 hour difference? Is it some sort of git
config setting that renders the time in a different zone or something? Or,
are we calculating incorrectly?

**Comment by MikeBosw** [comment]
Yeah. Not sure. I'm guessing the actual seconds are the same, but haven't
confirmed.

**Comment by jbrukh** [comment]
Yeah, I believe the seconds should be the same also. Otherwise, that would
imply some sort of parsing bug of numbers, which is highly unlikely.

**Comment by jbrukh** [comment]
Since your change with cat-file, ggcompare passes on that commit.
