### ISSUE TITLE
ggcompare fails on ggit repo (commit a4e7875d) with "index out of range".

### ISSUE THREAD

**Issue by jbrukh** [jbrukh/ggit#41]
...
1400 git/ggit object: ffffe11c6406ff6224a077f3d54680655440975e
.git :  cat-file -p ffffe11c6406ff6224a077f3d54680655440975e
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jbrukh/ggit/api.(_Idx).entryById(0x105dfea0, 0x11096f60, 0x28, 0x1069f140, 0x2, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:118 +0x6e
github.com/jbrukh/ggit/api.(_Pack).unpack(0x105dfe10, 0x10673b60, 0x0, 0x0, 0x10694400, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:130 +0x83
github.com/jbrukh/ggit/api.unpack(0x105de358, 0x2, 0x2, 0x10673b60, 0x0, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/pack.go:182 +0x75
github.com/jbrukh/ggit/api.(*DiskRepository).ObjectFromOid(0x1060c880, 0x10673b60, 0x0, 0x0, 0x0, ...)
    /Users/brukhman/other/src/github.com/jbrukh/ggit/api/disk_repository.go:63 +0xeb
main.main()
    /Users/brukhman/other/src/github.com/jbrukh/ggit/cmd/ggcompare/ggcompare.go:50 +0x4a8

goroutine 2 [syscall]:
created by runtime.main
    /usr/local/go/src/pkg/runtime/proc.c:221

goroutine 12 [finalizer wait]:
created by runtime.gc
    /usr/local/go/src/pkg/runtime/mgc0.c:882

**Comment by jbrukh** [comment]
ggcompare is proving to be an effective tool. :)

**Comment by MikeBosw** [comment]
still seeing this?

**Comment by jbrukh** [comment]
LGTM! Closing.
